// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xeuclidean.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XEuclidean_CfgInitialize(XEuclidean *InstancePtr, XEuclidean_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Bus_in_BaseAddress = ConfigPtr->Bus_in_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XEuclidean_Start(XEuclidean *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEuclidean_ReadReg(InstancePtr->Bus_in_BaseAddress, XEUCLIDEAN_BUS_IN_ADDR_AP_CTRL) & 0x80;
    XEuclidean_WriteReg(InstancePtr->Bus_in_BaseAddress, XEUCLIDEAN_BUS_IN_ADDR_AP_CTRL, Data | 0x01);
}

u32 XEuclidean_IsDone(XEuclidean *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEuclidean_ReadReg(InstancePtr->Bus_in_BaseAddress, XEUCLIDEAN_BUS_IN_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XEuclidean_IsIdle(XEuclidean *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEuclidean_ReadReg(InstancePtr->Bus_in_BaseAddress, XEUCLIDEAN_BUS_IN_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XEuclidean_IsReady(XEuclidean *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEuclidean_ReadReg(InstancePtr->Bus_in_BaseAddress, XEUCLIDEAN_BUS_IN_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XEuclidean_EnableAutoRestart(XEuclidean *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEuclidean_WriteReg(InstancePtr->Bus_in_BaseAddress, XEUCLIDEAN_BUS_IN_ADDR_AP_CTRL, 0x80);
}

void XEuclidean_DisableAutoRestart(XEuclidean *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEuclidean_WriteReg(InstancePtr->Bus_in_BaseAddress, XEUCLIDEAN_BUS_IN_ADDR_AP_CTRL, 0);
}

void XEuclidean_Set_con(XEuclidean *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEuclidean_WriteReg(InstancePtr->Bus_in_BaseAddress, XEUCLIDEAN_BUS_IN_ADDR_CON_DATA, Data);
}

u32 XEuclidean_Get_con(XEuclidean *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEuclidean_ReadReg(InstancePtr->Bus_in_BaseAddress, XEUCLIDEAN_BUS_IN_ADDR_CON_DATA);
    return Data;
}

void XEuclidean_Set_tresh(XEuclidean *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEuclidean_WriteReg(InstancePtr->Bus_in_BaseAddress, XEUCLIDEAN_BUS_IN_ADDR_TRESH_DATA, Data);
}

u32 XEuclidean_Get_tresh(XEuclidean *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEuclidean_ReadReg(InstancePtr->Bus_in_BaseAddress, XEUCLIDEAN_BUS_IN_ADDR_TRESH_DATA);
    return Data;
}

void XEuclidean_InterruptGlobalEnable(XEuclidean *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEuclidean_WriteReg(InstancePtr->Bus_in_BaseAddress, XEUCLIDEAN_BUS_IN_ADDR_GIE, 1);
}

void XEuclidean_InterruptGlobalDisable(XEuclidean *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEuclidean_WriteReg(InstancePtr->Bus_in_BaseAddress, XEUCLIDEAN_BUS_IN_ADDR_GIE, 0);
}

void XEuclidean_InterruptEnable(XEuclidean *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XEuclidean_ReadReg(InstancePtr->Bus_in_BaseAddress, XEUCLIDEAN_BUS_IN_ADDR_IER);
    XEuclidean_WriteReg(InstancePtr->Bus_in_BaseAddress, XEUCLIDEAN_BUS_IN_ADDR_IER, Register | Mask);
}

void XEuclidean_InterruptDisable(XEuclidean *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XEuclidean_ReadReg(InstancePtr->Bus_in_BaseAddress, XEUCLIDEAN_BUS_IN_ADDR_IER);
    XEuclidean_WriteReg(InstancePtr->Bus_in_BaseAddress, XEUCLIDEAN_BUS_IN_ADDR_IER, Register & (~Mask));
}

void XEuclidean_InterruptClear(XEuclidean *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEuclidean_WriteReg(InstancePtr->Bus_in_BaseAddress, XEUCLIDEAN_BUS_IN_ADDR_ISR, Mask);
}

u32 XEuclidean_InterruptGetEnabled(XEuclidean *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XEuclidean_ReadReg(InstancePtr->Bus_in_BaseAddress, XEUCLIDEAN_BUS_IN_ADDR_IER);
}

u32 XEuclidean_InterruptGetStatus(XEuclidean *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XEuclidean_ReadReg(InstancePtr->Bus_in_BaseAddress, XEUCLIDEAN_BUS_IN_ADDR_ISR);
}

