// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// BUS_IN
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of con
//        bit 31~0 - con[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of tresh
//        bit 31~0 - tresh[31:0] (Read/Write)
// 0x1c : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XEUCLIDEAN_BUS_IN_ADDR_AP_CTRL    0x00
#define XEUCLIDEAN_BUS_IN_ADDR_GIE        0x04
#define XEUCLIDEAN_BUS_IN_ADDR_IER        0x08
#define XEUCLIDEAN_BUS_IN_ADDR_ISR        0x0c
#define XEUCLIDEAN_BUS_IN_ADDR_CON_DATA   0x10
#define XEUCLIDEAN_BUS_IN_BITS_CON_DATA   32
#define XEUCLIDEAN_BUS_IN_ADDR_TRESH_DATA 0x18
#define XEUCLIDEAN_BUS_IN_BITS_TRESH_DATA 32

