// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XEUCLIDEAN_H
#define XEUCLIDEAN_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xeuclidean_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Bus_in_BaseAddress;
} XEuclidean_Config;
#endif

typedef struct {
    u32 Bus_in_BaseAddress;
    u32 IsReady;
} XEuclidean;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XEuclidean_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XEuclidean_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XEuclidean_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XEuclidean_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XEuclidean_Initialize(XEuclidean *InstancePtr, u16 DeviceId);
XEuclidean_Config* XEuclidean_LookupConfig(u16 DeviceId);
int XEuclidean_CfgInitialize(XEuclidean *InstancePtr, XEuclidean_Config *ConfigPtr);
#else
int XEuclidean_Initialize(XEuclidean *InstancePtr, const char* InstanceName);
int XEuclidean_Release(XEuclidean *InstancePtr);
#endif

void XEuclidean_Start(XEuclidean *InstancePtr);
u32 XEuclidean_IsDone(XEuclidean *InstancePtr);
u32 XEuclidean_IsIdle(XEuclidean *InstancePtr);
u32 XEuclidean_IsReady(XEuclidean *InstancePtr);
void XEuclidean_EnableAutoRestart(XEuclidean *InstancePtr);
void XEuclidean_DisableAutoRestart(XEuclidean *InstancePtr);

void XEuclidean_Set_con(XEuclidean *InstancePtr, u32 Data);
u32 XEuclidean_Get_con(XEuclidean *InstancePtr);
void XEuclidean_Set_tresh(XEuclidean *InstancePtr, u32 Data);
u32 XEuclidean_Get_tresh(XEuclidean *InstancePtr);

void XEuclidean_InterruptGlobalEnable(XEuclidean *InstancePtr);
void XEuclidean_InterruptGlobalDisable(XEuclidean *InstancePtr);
void XEuclidean_InterruptEnable(XEuclidean *InstancePtr, u32 Mask);
void XEuclidean_InterruptDisable(XEuclidean *InstancePtr, u32 Mask);
void XEuclidean_InterruptClear(XEuclidean *InstancePtr, u32 Mask);
u32 XEuclidean_InterruptGetEnabled(XEuclidean *InstancePtr);
u32 XEuclidean_InterruptGetStatus(XEuclidean *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
